name: CI2
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: eribeirofit/cse4001:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        # Activate unity
        - name: test run command
          id: run-os161
          run: cd /root/os161/root/ && /root/os161/tools/bin/sys161 kernel q 


